// Build step: turn the repo's projects/ folder into the web app's library.
//
// Source of truth is projects/<slug>/manifest.json (written by the research
// agent's publish step). This script reads every manifest, copies web-servable
// artifacts into public/library/<slug>/, renders report.md to HTML, and emits
// lib/library.generated.ts — a static module the app imports. Run automatically
// before `dev` and `build` (see package.json), so the web app always reflects
// whatever has been researched, with no manual curation.

import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, extname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { renderMarkdown } from "./markdown.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const WEB = join(HERE, "..");
const REPO = join(WEB, "..");
const PROJECTS_DIR = join(REPO, "projects");
const PUBLIC_LIB = join(WEB, "public", "library");
const OUT_MODULE = join(WEB, "lib", "library.generated.ts");

// Files the browser can serve directly. report.md is handled separately
// (rendered to HTML); everything else here is copied verbatim and linked.
const SERVABLE = new Set([".html", ".png", ".svg", ".jpg", ".jpeg", ".gif", ".webp", ".pdf"]);

function readManifest(projectPath) {
  const manifestPath = join(projectPath, "manifest.json");
  if (!existsSync(manifestPath)) return null;
  try {
    return JSON.parse(readFileSync(manifestPath, "utf8"));
  } catch {
    console.warn(`[build-library] skipping ${projectPath}: invalid manifest.json`);
    return null;
  }
}

function collectArtifacts(projectPath, slug) {
  // Copy servable files into public/library/<slug>/ and return link metadata.
  const artifacts = [];
  const destDir = join(PUBLIC_LIB, slug);
  for (const name of readdirSync(projectPath)) {
    if (name === "manifest.json" || name === "report.md") continue;
    const full = join(projectPath, name);
    if (!statSync(full).isFile()) continue;
    if (!SERVABLE.has(extname(name).toLowerCase())) continue;
    mkdirSync(destDir, { recursive: true });
    cpSync(full, join(destDir, name));
    artifacts.push({ name, url: `/library/${slug}/${name}`, ext: extname(name).toLowerCase() });
  }
  return artifacts;
}

function artifactKind(ext) {
  if (ext === ".html") return "deck";
  if (ext === ".pdf") return "document";
  if ([".png", ".svg", ".jpg", ".jpeg", ".gif", ".webp"].includes(ext)) return "image";
  return "file";
}

function buildProject(projectPath, manifest) {
  const slug = manifest.slug || projectPath.split("/").pop();
  const files = collectArtifacts(projectPath, slug);

  const reportPath = join(projectPath, "report.md");
  const reportHtml = existsSync(reportPath)
    ? renderMarkdown(readFileSync(reportPath, "utf8"))
    : "";

  const artifacts = files.map((f) => ({
    type: artifactKind(f.ext),
    name: f.name,
    url: f.url,
  }));

  return {
    slug,
    title: manifest.title || slug,
    topic: manifest.topic || "",
    summary: manifest.summary || "",
    tags: Array.isArray(manifest.tags) ? manifest.tags : [],
    created: manifest.created || "",
    updated: manifest.updated || manifest.created || "",
    version: manifest.version || 1,
    sources: Array.isArray(manifest.sources) ? manifest.sources : [],
    related: Array.isArray(manifest.related) ? manifest.related : [],
    changelog: Array.isArray(manifest.changelog) ? manifest.changelog : [],
    artifacts,
    hasReport: reportHtml.length > 0,
    reportHtml,
  };
}

function main() {
  // Start from a clean public/library so deleted/renamed projects don't linger.
  rmSync(PUBLIC_LIB, { recursive: true, force: true });

  const projects = [];
  if (existsSync(PROJECTS_DIR)) {
    for (const entry of readdirSync(PROJECTS_DIR)) {
      const projectPath = join(PROJECTS_DIR, entry);
      if (!statSync(projectPath).isDirectory()) continue;
      const manifest = readManifest(projectPath);
      if (!manifest) continue;
      projects.push(buildProject(projectPath, manifest));
    }
  }

  // Newest first, by updated date then version.
  projects.sort((a, b) => {
    if (a.updated !== b.updated) return a.updated < b.updated ? 1 : -1;
    return (b.version || 0) - (a.version || 0);
  });

  const banner =
    "// AUTO-GENERATED by scripts/build-library.mjs — do not edit by hand.\n" +
    "// Regenerated before every dev/build run from the repo's projects/ folder.\n";
  const body = `export const LIBRARY = ${JSON.stringify(projects, null, 2)} as const;\n`;

  mkdirSync(dirname(OUT_MODULE), { recursive: true });
  writeFileSync(OUT_MODULE, banner + body);

  console.log(`[build-library] wrote ${projects.length} project(s) to library.generated.ts`);
}

main();
