"""HTML email generation tool."""

from __future__ import annotations

import base64
import json
from pathlib import Path
from typing import Any

from claude_agent_sdk import tool

# Reliability tier to color dot mapping
TIER_DOTS = {
    "established": "&#x1F7E2;",  # Green circle
    "reputable": "&#x1F535;",     # Blue circle
    "emerging": "&#x1F7E1;",      # Yellow circle
    "opinion": "&#x1F534;",       # Red circle
    "unknown": "&#x26AA;",        # White circle
}

EMAIL_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 680px; margin: 0 auto; padding: 20px; color: #333; line-height: 1.6;">

<h1 style="color: #29417a; border-bottom: 3px solid #29417a; padding-bottom: 12px; font-size: 24px;">
  {title}
</h1>

<div style="background: #f0f4f8; padding: 16px 20px; border-radius: 8px; margin: 16px 0; border-left: 4px solid #29417a;">
  <h2 style="margin: 0 0 8px 0; font-size: 16px; color: #29417a;">Key Takeaways</h2>
  <ul style="margin: 0; padding-left: 20px;">
    {takeaways_html}
  </ul>
</div>

{sections_html}

<div style="background: #f8f9fa; padding: 16px 20px; border-radius: 8px; margin: 24px 0;">
  <h2 style="margin: 0 0 12px 0; font-size: 16px; color: #29417a;">Executive Summary</h2>
  <p style="margin: 0; font-size: 14px; color: #555;">{executive_summary}</p>
</div>

<div style="border-top: 1px solid #e2e8f0; padding-top: 16px; margin-top: 24px;">
  <h3 style="font-size: 14px; color: #666; margin-bottom: 8px;">Sources</h3>
  {sources_html}
</div>

<div style="text-align: center; padding: 16px; margin-top: 24px; font-size: 12px; color: #999;">
  Generated by Research Agent
</div>

</body>
</html>
"""


def _image_to_base64(path: str) -> str | None:
    """Convert an image file to base64 data URI."""
    p = Path(path)
    if not p.exists():
        return None
    try:
        data = p.read_bytes()
        ext = p.suffix.lower()
        mime = {"png": "image/png", "jpg": "image/jpeg", "jpeg": "image/jpeg", "svg": "image/svg+xml"}.get(
            ext.lstrip("."), "image/png"
        )
        return f"data:{mime};base64,{base64.b64encode(data).decode()}"
    except Exception:
        return None


def _render_email(report_data: dict, output_path: str, diagram_paths: list[str]) -> str:
    """Render a ReportDraft dict to an HTML email."""
    # Takeaways
    takeaways = report_data.get("key_takeaways", [])
    takeaways_html = "\n    ".join(
        f'<li style="margin-bottom: 4px; font-size: 14px;">{t}</li>'
        for t in takeaways
    )

    # Sections (truncated for email — top 3 sections)
    sections = report_data.get("sections", [])[:3]
    diagram_iter = iter(diagram_paths or [])
    sections_parts = []
    for section in sections:
        content = section.get("content", "")
        # Truncate to ~200 chars for email
        if len(content) > 300:
            content = content[:297] + "..."

        section_html = f"""
<div style="margin: 20px 0;">
  <h2 style="font-size: 18px; color: #29417a; margin-bottom: 8px;">{section.get('title', '')}</h2>
  <p style="font-size: 14px; color: #444; margin: 0;">{content}</p>"""

        # Try to add a diagram
        diagram = next(diagram_iter, None)
        if diagram:
            data_uri = _image_to_base64(diagram)
            if data_uri:
                section_html += f'\n  <img src="{data_uri}" style="max-width: 100%; margin: 12px 0; border-radius: 4px;" alt="Diagram">'

        section_html += "\n</div>"
        sections_parts.append(section_html)

    sections_html = "\n".join(sections_parts)

    # Sources
    sources = report_data.get("sources", [])
    source_parts = []
    for src in sources[:10]:
        tier = src.get("reliability_tier", "unknown")
        dot = TIER_DOTS.get(tier, TIER_DOTS["unknown"])
        url = src.get("url", "#")
        title = src.get("title", "Untitled")
        source_parts.append(
            f'<p style="margin: 4px 0; font-size: 13px;">{dot} <a href="{url}" style="color: #4682b4; text-decoration: none;">{title}</a></p>'
        )
    sources_html = "\n  ".join(source_parts)

    html = EMAIL_TEMPLATE.format(
        title=report_data.get("title", "Research Report"),
        takeaways_html=takeaways_html,
        sections_html=sections_html,
        executive_summary=report_data.get("executive_summary", ""),
        sources_html=sources_html,
    )

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(html, encoding="utf-8")
    return str(output)


@tool(
    "render_email",
    "Render a structured research report into a formatted HTML email. Pass the report as a JSON string. The email is concise with key takeaways, top findings, and embedded diagrams.",
    {
        "type": "object",
        "properties": {
            "report_json": {"type": "string", "description": "JSON-serialized ReportDraft"},
            "output_path": {"type": "string", "description": "Path for the output .html file"},
            "diagram_paths": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Paths to diagram images to embed as base64",
            },
        },
        "required": ["report_json", "output_path"],
    },
)
async def render_email(args: dict[str, Any]) -> dict[str, Any]:
    """Generate an HTML email from report data."""
    try:
        report_data = json.loads(args["report_json"])
        diagram_paths = args.get("diagram_paths", [])
        path = _render_email(report_data, args["output_path"], diagram_paths)
        return {
            "content": [{"type": "text", "text": f"HTML email saved to: {path}"}]
        }
    except Exception as e:
        return {
            "content": [
                {"type": "text", "text": f"ERROR: Failed to generate HTML email: {e}"}
            ]
        }
